### PR TITLE
early detection of missing methods

### PR DESCRIPTION
**Pull request by jcupitt**
__getattr__ is supposed to raise AttributeError for missing methods, and
do it at the time of call, not later. This should help eg. numpy array
integration.

See https://github.com/libvips/pyvips/issues/314

### CODE REVIEW

**Comment by jcupitt** [comment]
With this change I now see:

```
$ python3
Python 3.9.7 (default, Sep 10 2021, 14:59:43) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> pyvips.Image.banana
Traceback (most recent call last):
  File "/home/john/GIT/pyvips/pyvips/vimage.py", line 136, in __getattr__
    intro = Introspect.get(name)
  File "/home/john/GIT/pyvips/pyvips/voperation.py", line 153, in get
    cls._introspect_cache[operation_name] = Introspect(operation_name)
  File "/home/john/GIT/pyvips/pyvips/voperation.py", line 39, in __init__
    op = Operation.new_from_name(operation_name)
  File "/home/john/GIT/pyvips/pyvips/voperation.py", line 193, in new_from_name
    raise Error('no such operation {0}'.format(operation_name))
pyvips.error.Error: no such operation banana
  VipsOperation: class "banana" not found


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/john/GIT/pyvips/pyvips/vimage.py", line 140, in __getattr__
    raise AttributeError
AttributeError
>>> x = pyvips.Image.black(10, 10)
>>> x.banana
Traceback (most recent call last):
  File "/home/john/GIT/pyvips/pyvips/vimage.py", line 967, in __getattr__
    intro = Introspect.get(name)
  File "/home/john/GIT/pyvips/pyvips/voperation.py", line 153, in get
    cls._introspect_cache[operation_name] = Introspect(operation_name)
  File "/home/john/GIT/pyvips/pyvips/voperation.py", line 39, in __init__
    op = Operation.new_from_name(operation_name)
  File "/home/john/GIT/pyvips/pyvips/voperation.py", line 193, in new_from_name
    raise Error('no such operation {0}'.format(operation_name))
pyvips.error.Error: no such operation banana
  VipsOperation: class "banana" not found


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/john/GIT/pyvips/pyvips/vimage.py", line 971, in __getattr__
    raise AttributeError
AttributeError
>>> 
```

ie. missing methods are detected immediately rather than detection being deferred until invocation.

**Comment by erdmann** [comment]
[Yes, We Have No Bananas](https://www.youtube.com/watch?v=8QqkrIDeTeA)

**Comment by erdmann** [comment]
I tested this and it does the trick for me!   It enables straightforward extension to do lots of cool stuff, especially in IPython:
image

Thanks!

**Comment by jcupitt** [comment]
Oh, nice!

**Pull request merged**
