### PR TITLE
Add the guint64 type to GValue

### PR DESCRIPTION
**Pull request by kleisauke**
Because libvips can use the `VIPS_ARG_UINT64` macro (see for e.g. the `offset` argument in `rawload`).

This PR also updates the copyright year in the docs.

### CODE REVIEW

**Comment by jcupitt** [comment]
Nice!

**Comment by jcupitt** [comment]
Oh, would you mind adding a line to the CHANGELOG too?

**Comment by kleisauke** [comment]
See https://github.com/libvips/pyvips/commit/40d910fa222c2262732c5c2718398b3e7cd8c4d6.

In that commit, I've also added a unit test for this and changed the `unsigned long` to `uint64_t` (to make sure that it is at least 64 bits).

**Comment by jcupitt** [comment]
Looks good. I should have spotted the `uint64` thing, I was reading too quickly.

**Pull request merged**
